repository:
    name: proton
    owner: kolosys
    description: '[![Go Reference](https://pkg.go.dev/badge/github.com/kolosys/proton.svg)](https://pkg.go.dev/github.com/kolosys/proton)'
    import_path: github.com/kolosys/proton
    branch: main
    url: https://github.com/kolosys/proton
output:
    directory: D:\Projects\kolosys\proton\docs
    clean: true
    gitbook_config: true
discovery:
    packages:
        auto_discover: true
        include_patterns:
            - ./...
        exclude_patterns:
            - ./vendor/...
            - ./test/...
            - ./.git/...
            - '**/*_test.go'
        manual_packages: []
    api_generation:
        enabled: true
        include_unexported: false
        include_tests: false
        include_examples: true
    examples:
        enabled: true
        auto_discover: true
        directories: []
    guides:
        enabled: true
        include_contributing: true
        include_faq: true
        custom_guides: []
templates:
    directory: ""
    custom_templates: []
gitbook:
    title: proton
    description: '[![Go Reference](https://pkg.go.dev/badge/github.com/kolosys/proton.svg)](https://pkg.go.dev/github.com/kolosys/proton)'
    theme: default
    plugins: []
    structure:
        readme: README.md
        summary: SUMMARY.md
metadata:
    version: latest
    go_version: ""
    author: ""
    license: MIT
generation:
    date_format: "2006-01-02"
    include_generated_notice: true
    include_toc: true
    max_depth: 3
